



import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.awt.event.ActionEvent;
import java.sql.Timestamp;
import java.util.Collections;
import javax.swing.table.DefaultTableModel;
import javax.swing.JTable;
import java.util.stream.Collectors;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author diane
 */
public class CourseSchedulerGUI extends javax.swing.JFrame {

    /**
     * Creates new form CourseSchedulerGUI
     */
    
    private String currentSemester;
    private String courses;
    private String course;
    private String course_code;
    private String student_ID;
    private String student;
    private String status;
    private Object addCoursesStatusLabel;
    
    private DefaultTableModel model;
    
    public CourseSchedulerGUI() {
        initComponents();
        rebuildSemesterComboBoxes();
        rebuildCourseComboBoxes();
        rebuildStudentComboBoxes();
    }
    
    //semester
    public void rebuildSemesterComboBoxes()
    {
        ArrayList<String> semester = SemesterQueries.getSemesterList();
        ChangeSemesterComboBox.setModel(new javax.swing.DefaultComboBoxModel(semester.toArray()));
        if (semester.size() == 0)
        {
            addSemesterStatusLabel.setText("None, add a semester.");
            currentSemester = "None";
        }

    }
    
    //course
    public void rebuildCourseComboBoxes()
    {
        ArrayList<String> courseCode = CourseQueries.getAllCourseCodes(currentSemester);
        ChangeCourseComboBox.setModel(new javax.swing.DefaultComboBoxModel(courseCode.toArray()));
        DisplayCourseListStudentsComboBox.setModel(new javax.swing.DefaultComboBoxModel(courseCode.toArray()));
        AdminDropCourseComboBox.setModel(new javax.swing.DefaultComboBoxModel(courseCode.toArray()));
        StudentDropCourseComboBox.setModel(new javax.swing.DefaultComboBoxModel(courseCode.toArray()));
    }
    
    public void rebuildStudentComboBoxes()
    {
        ArrayList<String> student = StudentQueries.getAllStudentID();
        selectStudentComboBox.setModel(new javax.swing.DefaultComboBoxModel(student.toArray()));
        DisplayScheduleStudentComboBox.setModel(new javax.swing.DefaultComboBoxModel(student.toArray()));
        AdminDropStudentComboBox.setModel(new javax.swing.DefaultComboBoxModel(student.toArray()));
        currentStudentComboBox.setModel(new javax.swing.DefaultComboBoxModel(student.toArray()));
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        currentSemesterLabel = new javax.swing.JLabel();
        ChangeSemesterComboBox = new javax.swing.JComboBox<>();
        ChangeSemesterButton = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        SemesterNameJLabel = new javax.swing.JLabel();
        addSemesterTextField = new javax.swing.JTextField();
        AddSemesterSubmitButton = new javax.swing.JButton();
        addSemesterStatusLabel = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        addStudentIDTextField = new javax.swing.JTextField();
        FirstNameTextField = new javax.swing.JTextField();
        LastNameTextField = new javax.swing.JTextField();
        addStudentButton = new javax.swing.JButton();
        addStudentStatusLabel = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        addCourseButton = new javax.swing.JButton();
        addCourseCodeTextField = new javax.swing.JTextField();
        addCourseDescriptionTextField = new javax.swing.JTextField();
        addCourseSeatsSpinner = new javax.swing.JSpinner();
        addCourseStatusLabel = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        DisplayCourseListStudentsComboBox = new javax.swing.JComboBox<>();
        DisplayCourseListStudentsButton = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        WaitlistedCourseListStudentsTable = new javax.swing.JTable();
        jScrollPane5 = new javax.swing.JScrollPane();
        ScheduledCourseListStudentsTable = new javax.swing.JTable();
        jPanel10 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        AdminDropStudentComboBox = new javax.swing.JComboBox<>();
        AdminDropStudentButton = new javax.swing.JButton();
        jScrollPane6 = new javax.swing.JScrollPane();
        AdminDropStudentTextArea = new javax.swing.JTextArea();
        jPanel11 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        AdminDropCourseComboBox = new javax.swing.JComboBox<>();
        AdminDropCourseButton = new javax.swing.JButton();
        jScrollPane7 = new javax.swing.JScrollPane();
        DropCourseTextArea = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();
        jTabbedPane4 = new javax.swing.JTabbedPane();
        jPanel6 = new javax.swing.JPanel();
        displayCoursesButton = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        displayCoursesTable = new javax.swing.JTable();
        jPanel7 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        ScheduleCoursesLabel = new javax.swing.JLabel();
        selectStudentComboBox = new javax.swing.JComboBox<>();
        ChangeCourseComboBox = new javax.swing.JComboBox<>();
        scheduleCourseSubmitButton = new javax.swing.JButton();
        scheduleCoursesStatusLabel = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        DisplayScheduleStudentComboBox = new javax.swing.JComboBox<>();
        displayScheduleButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        displayScheduleTable = new javax.swing.JTable();
        jPanel12 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        StudentDropCourseButton = new javax.swing.JButton();
        StudentDropCourseComboBox = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        StudentDropCourseTextArea = new javax.swing.JTextArea();
        jLabel18 = new javax.swing.JLabel();
        currentStudentComboBox = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 255));
        jLabel1.setText("Course Scheduler");

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel2.setText("Current Semester:");

        currentSemesterLabel.setText("None");

        ChangeSemesterComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        ChangeSemesterButton.setText("Change Semester");
        ChangeSemesterButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChangeSemesterButtonActionPerformed(evt);
            }
        });

        SemesterNameJLabel.setText("Semester Name:");

        addSemesterTextField.setColumns(20);

        AddSemesterSubmitButton.setText("Submit");
        AddSemesterSubmitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddSemesterSubmitButtonActionPerformed(evt);
            }
        });

        addSemesterStatusLabel.setText("       ");
        addSemesterStatusLabel.setToolTipText("");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(SemesterNameJLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(addSemesterTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(addSemesterStatusLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                            .addGap(204, 204, 204)
                            .addComponent(AddSemesterSubmitButton))))
                .addContainerGap(481, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SemesterNameJLabel)
                    .addComponent(addSemesterTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(AddSemesterSubmitButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(addSemesterStatusLabel)
                .addContainerGap(366, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Add Semester", jPanel3);

        jLabel6.setText("Student ID: ");

        jLabel7.setText("FirstName: ");

        jLabel8.setText("Last Name: ");

        addStudentButton.setText("Submit");
        addStudentButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addStudentButtonActionPerformed(evt);
            }
        });

        addStudentStatusLabel.setText("                                                                  ");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(225, 225, 225)
                        .addComponent(addStudentButton))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel7)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(addStudentIDTextField)
                            .addComponent(FirstNameTextField)
                            .addComponent(LastNameTextField)
                            .addComponent(addStudentStatusLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(447, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(addStudentIDTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(FirstNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(LastNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(addStudentButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                .addComponent(addStudentStatusLabel)
                .addGap(93, 93, 93))
        );

        jTabbedPane2.addTab("Add Student", jPanel4);

        jLabel3.setText("Course Code:");

        jLabel4.setText("Course Description: ");

        jLabel5.setText("Seats: ");

        addCourseButton.setText("Submit");
        addCourseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addCourseButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3))
                .addGap(42, 42, 42)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(addCourseCodeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(addCourseDescriptionTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(addCourseSeatsSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(315, Short.MAX_VALUE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(addCourseButton)
                            .addComponent(addCourseStatusLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(addCourseCodeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(addCourseDescriptionTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(32, 32, 32)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(addCourseSeatsSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(addCourseStatusLabel)
                .addGap(21, 21, 21)
                .addComponent(addCourseButton, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(184, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Add Course", jPanel5);

        jLabel13.setText("Select Course: ");

        DisplayCourseListStudentsComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        DisplayCourseListStudentsButton.setText("Display");
        DisplayCourseListStudentsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DisplayCourseListStudentsButtonActionPerformed(evt);
            }
        });

        jLabel14.setText("Scheduled Students");

        jLabel15.setText("Waitlisted Students");

        WaitlistedCourseListStudentsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "LastName", "FirstName", "StudentID"
            }
        ));
        jScrollPane4.setViewportView(WaitlistedCourseListStudentsTable);

        ScheduledCourseListStudentsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "LastName", "FirstName", "StudentID"
            }
        ));
        jScrollPane5.setViewportView(ScheduledCourseListStudentsTable);

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel9Layout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addGap(18, 18, 18)
                                .addComponent(DisplayCourseListStudentsComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel14))
                        .addGap(42, 42, 42)
                        .addComponent(DisplayCourseListStudentsButton))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 413, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 413, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15))))
                .addContainerGap(353, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(DisplayCourseListStudentsComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DisplayCourseListStudentsButton))
                .addGap(18, 18, 18)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Display Course List of Students", jPanel9);

        jLabel16.setText("Select Student:");

        AdminDropStudentComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        AdminDropStudentButton.setText("Drop Student");
        AdminDropStudentButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdminDropStudentButtonActionPerformed(evt);
            }
        });

        AdminDropStudentTextArea.setColumns(20);
        AdminDropStudentTextArea.setRows(5);
        jScrollPane6.setViewportView(AdminDropStudentTextArea);

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 484, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addGap(53, 53, 53)
                        .addComponent(AdminDropStudentComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(AdminDropStudentButton)))
                .addContainerGap(302, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(AdminDropStudentComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AdminDropStudentButton))
                .addGap(35, 35, 35)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(115, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Drop Student", jPanel10);

        jLabel17.setText("Select Course to be Dropped:");

        AdminDropCourseComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        AdminDropCourseButton.setText("Drop Course");
        AdminDropCourseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdminDropCourseButtonActionPerformed(evt);
            }
        });

        DropCourseTextArea.setColumns(20);
        DropCourseTextArea.setRows(5);
        jScrollPane7.setViewportView(DropCourseTextArea);

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 494, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addGap(18, 18, 18)
                        .addComponent(AdminDropCourseComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(47, 47, 47)
                        .addComponent(AdminDropCourseButton)))
                .addContainerGap(291, Short.MAX_VALUE))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(AdminDropCourseComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AdminDropCourseButton))
                .addGap(42, 42, 42)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(53, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Drop Course", jPanel11);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane2))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane2, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        jTabbedPane1.addTab("Admin", jPanel1);

        displayCoursesButton.setText("Display");
        displayCoursesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                displayCoursesButtonActionPerformed(evt);
            }
        });

        displayCoursesTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Course Code", "Description", "Seats"
            }
        ));
        jScrollPane3.setViewportView(displayCoursesTable);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(498, 498, 498)
                        .addComponent(displayCoursesButton))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 478, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(249, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(displayCoursesButton)
                .addGap(63, 63, 63))
        );

        jTabbedPane4.addTab("Display Courses", jPanel6);

        jLabel9.setText("Select Course: ");

        jLabel10.setText("Select Student:");

        ScheduleCoursesLabel.setText("   ");

        selectStudentComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        ChangeCourseComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        scheduleCourseSubmitButton.setText("Submit");
        scheduleCourseSubmitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                scheduleCourseSubmitButtonActionPerformed(evt);
            }
        });

        scheduleCoursesStatusLabel.setText("                                                                   ");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addComponent(scheduleCoursesStatusLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ScheduleCoursesLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPanel7Layout.createSequentialGroup()
                            .addComponent(jLabel9)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ChangeCourseComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel7Layout.createSequentialGroup()
                            .addComponent(jLabel10)
                            .addGap(30, 30, 30)
                            .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(scheduleCourseSubmitButton)
                                .addComponent(selectStudentComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(ChangeCourseComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(selectStudentComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addComponent(scheduleCourseSubmitButton)
                .addGap(30, 30, 30)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ScheduleCoursesLabel)
                    .addComponent(scheduleCoursesStatusLabel))
                .addContainerGap(189, Short.MAX_VALUE))
        );

        jTabbedPane4.addTab("Schedule Courses", jPanel7);

        jLabel11.setText("Select Student: ");

        DisplayScheduleStudentComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        displayScheduleButton.setText("Display");
        displayScheduleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                displayScheduleButtonActionPerformed(evt);
            }
        });

        displayScheduleTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "CourseCode", "Status"
            }
        ));
        jScrollPane1.setViewportView(displayScheduleTable);

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addGap(53, 53, 53)
                                .addComponent(DisplayScheduleStudentComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(290, 290, 290))
                            .addComponent(displayScheduleButton)))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 511, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(281, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(DisplayScheduleStudentComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addComponent(displayScheduleButton)
                .addContainerGap(70, Short.MAX_VALUE))
        );

        jTabbedPane4.addTab("Display Schedule", jPanel8);

        jLabel12.setText("Select Course: ");

        StudentDropCourseButton.setText("Drop Course");
        StudentDropCourseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StudentDropCourseButtonActionPerformed(evt);
            }
        });

        StudentDropCourseComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        StudentDropCourseTextArea.setColumns(20);
        StudentDropCourseTextArea.setRows(5);
        jScrollPane2.setViewportView(StudentDropCourseTextArea);

        jLabel18.setText("Current Student: ");

        currentStudentComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addGap(123, 123, 123)
                        .addComponent(StudentDropCourseButton))
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 463, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel12Layout.createSequentialGroup()
                                .addComponent(jLabel18)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(currentStudentComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel12Layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addGap(18, 18, 18)
                                .addComponent(StudentDropCourseComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(308, Short.MAX_VALUE))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(currentStudentComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(StudentDropCourseComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(StudentDropCourseButton)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(139, Short.MAX_VALUE))
        );

        jTabbedPane4.addTab("Drop Course", jPanel12);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane4)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane4, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        jTabbedPane4.getAccessibleContext().setAccessibleName("Display Courses");

        jTabbedPane1.addTab("Student", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTabbedPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(currentSemesterLabel)
                                .addGap(237, 237, 237)
                                .addComponent(ChangeSemesterComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(ChangeSemesterButton))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addComponent(jLabel1)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(currentSemesterLabel)
                    .addComponent(ChangeSemesterComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ChangeSemesterButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    

    private void ChangeSemesterButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChangeSemesterButtonActionPerformed
        // TODO add your handling code here:
        String semester = ChangeSemesterComboBox.getSelectedItem().toString();
        currentSemesterLabel.setText(semester);
        currentSemester = semester;
        rebuildSemesterComboBoxes(); 
        rebuildCourseComboBoxes();
        rebuildStudentComboBoxes();
        
    }//GEN-LAST:event_ChangeSemesterButtonActionPerformed

    private void AddSemesterSubmitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddSemesterSubmitButtonActionPerformed
        // TODO add your handling code here:
        String semester = addSemesterTextField.getText();
        SemesterQueries.addSemester(semester);
        addSemesterStatusLabel.setText("Semester " + semester + " has been added.");
        currentSemesterLabel.setText(semester);
        rebuildSemesterComboBoxes();
        rebuildCourseComboBoxes();
        rebuildStudentComboBoxes();
    }//GEN-LAST:event_AddSemesterSubmitButtonActionPerformed

    //DISPLAY COURSES BUTTON 
    private void displayCoursesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_displayCoursesButtonActionPerformed
        // TODO add your handling code here:
        
        DefaultTableModel table = new DefaultTableModel();
        table.addColumn("Course Code");
        table.addColumn("Course Description");
        table.addColumn("Course Seats");
        
        ArrayList<String> allCourses = CourseQueries.getAllCourseCodes(currentSemester);
        for (int i = 0; i < allCourses.size(); i++)
        {
            table.addRow(new Object[] {allCourses.get(i), CourseQueries.getCourseDescription(currentSemester, allCourses.get(i)), CourseQueries.getCourseSeats(currentSemester, allCourses.get(i))});
        }
        displayCoursesTable.setModel(table);
        rebuildCourseComboBoxes();
        rebuildSemesterComboBoxes();
        rebuildStudentComboBoxes();
       
    }//GEN-LAST:event_displayCoursesButtonActionPerformed

    private void addCourseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addCourseButtonActionPerformed
        // TODO add your handling code here:
        String currentSemester = (String) currentSemesterLabel.getText();
        String courseCode = addCourseCodeTextField.getText();
        String courseDescription = addCourseDescriptionTextField.getText();
        int seats = (int)addCourseSeatsSpinner.getValue();
        CourseEntry course = new CourseEntry(currentSemester, courseCode, courseDescription, seats);   
        CourseQueries.addCourse(course);
        addCourseStatusLabel.setText(courseCode + " was added. ");
        rebuildCourseComboBoxes();
        rebuildSemesterComboBoxes();
        rebuildStudentComboBoxes();
    }//GEN-LAST:event_addCourseButtonActionPerformed

    //DISPLAY SCHEDULE BUTTON 
    private void displayScheduleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_displayScheduleButtonActionPerformed
        // TODO add your handling code here:
        DefaultTableModel scheduleTable = new DefaultTableModel();
        scheduleTable.addColumn("Course Code");
        scheduleTable.addColumn("Status");
        String courseCode = addCourseCodeTextField.getText();
        int seats = (int)addCourseSeatsSpinner.getValue();
        student_ID = (String) DisplayScheduleStudentComboBox.getSelectedItem();
        
        
        ArrayList<String> courseCodes = ScheduleQueries.getCourseCode(currentSemester, student_ID);
        for(int i=0; i<courseCodes.size(); i++)
        {
            String status = ScheduleQueries.getStatus(currentSemester, student_ID, courseCodes.get(i));
            
            if ("w".equals(status))
            {
                status = "waitlisted";
            }
            else
            {
                status = "scheduled";
            }
            
            scheduleTable.addRow(new Object[] {courseCodes.get(i), status});
        }
        displayScheduleTable.setModel(scheduleTable);
        rebuildCourseComboBoxes();
        rebuildSemesterComboBoxes();
        
    }//GEN-LAST:event_displayScheduleButtonActionPerformed

    private void addStudentButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addStudentButtonActionPerformed
        // TODO add your handling code here:
        String student_ID = addStudentIDTextField.getText();
        String firstName = FirstNameTextField.getText();
        String lastName = LastNameTextField.getText();
        StudentEntry entry = new StudentEntry(student_ID, firstName,lastName);
        StudentQueries.addStudent(entry);
        addStudentStatusLabel.setText(lastName + ", "  + firstName + " was added. ");
        rebuildCourseComboBoxes();
        rebuildSemesterComboBoxes();
        rebuildStudentComboBoxes();
    }//GEN-LAST:event_addStudentButtonActionPerformed

    //needs to add a row to Schedule_Entry table
    private void scheduleCourseSubmitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_scheduleCourseSubmitButtonActionPerformed
        // TODO add your handling code here:
        student_ID = (String) selectStudentComboBox.getSelectedItem();
        course_code = (String) ChangeCourseComboBox.getSelectedItem();
        int seats = CourseQueries.getCourseSeats(currentSemester, course_code);
        int count = ScheduleQueries.getScheduledStudentCount(currentSemester, course_code);
        Timestamp timestamp = new Timestamp(System.currentTimeMillis());
        String status;
        String statusPrint;
        
        if (seats > count) 
        {
            status = "s";
            statusPrint = "scheduled";
        }
        else
        {
            status = "w";
            statusPrint = "waitlisted";
        }
    
        ScheduleEntry entry = new ScheduleEntry(currentSemester, student_ID, course_code, status, timestamp);  
        ScheduleQueries.addScheduleEntry(entry);
        scheduleCoursesStatusLabel.setText("Student " + selectStudentComboBox.getSelectedItem() + " was " + statusPrint + " for " + course_code);

        rebuildSemesterComboBoxes();
    }//GEN-LAST:event_scheduleCourseSubmitButtonActionPerformed

    private void StudentDropCourseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StudentDropCourseButtonActionPerformed
        // TODO add your handling code here:
        String currentSemester = currentSemesterLabel.getText();
        String courseCode = (String) StudentDropCourseComboBox.getSelectedItem();
        String studentID = (String) currentStudentComboBox.getSelectedItem();
        
        String firstName = StudentQueries.getFirstName(studentID);
        String lastName = StudentQueries.getLastName(studentID);
        
        ScheduleQueries.dropStudentScheduleByCourse(currentSemester, studentID, courseCode);
        
        StudentDropCourseTextArea.setText(courseCode + " was dropped from " + lastName + ", " + firstName + " (student ID: " +  studentID + ") schedule.");
        
        ScheduleQueries.updateStudent(currentSemester, courseCode, studentID);
        
    }//GEN-LAST:event_StudentDropCourseButtonActionPerformed

    private void DisplayCourseListStudentsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DisplayCourseListStudentsButtonActionPerformed
        // TODO add your handling code here:
        DefaultTableModel ScheduledStudentsTable = new DefaultTableModel();
        ScheduledStudentsTable.addColumn("Last Name");
        ScheduledStudentsTable.addColumn("First Name");
        ScheduledStudentsTable.addColumn("Student ID");
        
        DefaultTableModel WaitlistedStudentsTable = new DefaultTableModel();
        WaitlistedStudentsTable.addColumn("Last Name");
        WaitlistedStudentsTable.addColumn("First Name");
        WaitlistedStudentsTable.addColumn("Student ID");
        
        String currentSemester = currentSemesterLabel.getText();
        String courseCode = (String) DisplayCourseListStudentsComboBox.getSelectedItem();
        
        ArrayList<String> scheduledStudentID = new ArrayList<>();
        ArrayList<String> waitlistStudentID = new ArrayList<>();
        
        scheduledStudentID = ScheduleQueries.getScheduledStudentsByCourse_String(currentSemester, courseCode);
        
        for(int i = 0 ;i < scheduledStudentID.size(); i++)
        {
            ScheduledStudentsTable.addRow(new Object[] {StudentQueries.getLastName(scheduledStudentID.get(i)), StudentQueries.getFirstName(scheduledStudentID.get(i)), scheduledStudentID.get(i)});
        }
        waitlistStudentID = ScheduleQueries.getWaitlistedStudentsByCourse_String(currentSemester, courseCode);
        
        for (int i = 0; i < waitlistStudentID.size(); i++)
        {
            WaitlistedStudentsTable.addRow(new Object[] {StudentQueries.getLastName(waitlistStudentID.get(i)), StudentQueries.getFirstName(waitlistStudentID.get(i)), waitlistStudentID.get(i)});
        }
        ScheduledCourseListStudentsTable.setModel(ScheduledStudentsTable);
        WaitlistedCourseListStudentsTable.setModel(WaitlistedStudentsTable);
        
    }//GEN-LAST:event_DisplayCourseListStudentsButtonActionPerformed

    private void AdminDropStudentButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdminDropStudentButtonActionPerformed
        // TODO add your handling code here:
        String currentSemester = (String) currentSemesterLabel.getText();
        String courseCode = (String) AdminDropCourseComboBox.getSelectedItem();
        String studentID = (String) AdminDropStudentComboBox.getSelectedItem();
        String studentDropped = "";
        String firstName = StudentQueries.getFirstName(studentID);
        String lastName = StudentQueries.getLastName(studentID);
        studentDropped = studentDropped + lastName + ", " + firstName + " has been dropped from the list of all students\n";
        
        ArrayList<String> semesterByStudent = ScheduleQueries.semesterByStudent(studentID);
        ArrayList<String> courseCodeByStudent = ScheduleQueries.courseCodeByStudent(studentID);
        
        String studentScheduled = "";
        
        for (int i = 0; i < semesterByStudent.size(); i++){
            String nextStudent = ScheduleQueries.getWaitlistedStudent(semesterByStudent.get(i), courseCodeByStudent.get(i));
            if (nextStudent != null){
                ScheduleQueries.updateStudent(semesterByStudent.get(i), courseCodeByStudent.get(i) , nextStudent);
                String lastName1 = StudentQueries.getLastName(nextStudent);
                String firstName1 = StudentQueries.getFirstName(nextStudent);
                studentScheduled = studentScheduled + "\n" + lastName1 + ", " + firstName1 + " " + nextStudent + " has been scheduled into " + courseCodeByStudent.get(i) + " in " + semesterByStudent.get(i) + ".";
            }
        }
        
        ArrayList<String> semester = (ArrayList<String>) semesterByStudent.stream().distinct().collect(Collectors.toList());
        long semesterCounts = semesterByStudent.stream().distinct().count();
        ArrayList<Integer> semesterCount = new ArrayList<>();
        
        for (int i=0;i<semesterCounts;i++)
        {
            semesterCount.add(Collections.frequency(semesterByStudent, semester.get(i)));
        }

        
        for (int i=0; i < semester.size();i++){
            int count = 0;
            studentDropped = studentDropped + "\nFor Semester: " + semester.get(i) + "\n";
            for (int j=0; j< semesterCount.get(i); j++){
                studentDropped = studentDropped + lastName + ", " + firstName + " has been dropped from " + courseCodeByStudent.get(count) + "\n";
                count ++;
            }
        }
        
        //dropping the student overall from student table
        StudentQueries.dropStudent(studentID);
        //dropping student from the schedule table (so all scheduled courses gone)
        ScheduleQueries.dropStudent(studentID);
        
        studentScheduled = studentScheduled + "\n\n" + lastName + ", " + firstName + " has been removed from all the student comboboxes.";
        
        AdminDropStudentTextArea.setText(studentDropped + studentScheduled);
        
        rebuildStudentComboBoxes();
        
    }//GEN-LAST:event_AdminDropStudentButtonActionPerformed

    private void AdminDropCourseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdminDropCourseButtonActionPerformed
        // TODO add your handling code here:
        String currentSemester = (String) currentSemesterLabel.getText();
        String courseCode = (String) AdminDropCourseComboBox.getSelectedItem();
        ArrayList<String> dropCourseStudents = ScheduleQueries.dropCourseStudentList(currentSemester, courseCode);
        String scheduledDropped = "Students scheduled dropped from the course: \n";
        String waitlistedDropped= "Students waitlisted that were dropped from the course: \n";  
        
        for(int i =0; i < dropCourseStudents.size(); i++)
        {
            String studentID = dropCourseStudents.get(i);
            String lastName = StudentQueries.getLastName(studentID);
            String firstName = StudentQueries.getFirstName(studentID);
            String status = ScheduleQueries.getStatus(currentSemester, studentID, courseCode);
            if (status.equals("s"))
            {
                scheduledDropped = scheduledDropped + lastName + ", " + firstName + " Student ID:" + studentID + "\n";
            }
            else
            {
                waitlistedDropped = waitlistedDropped + lastName + ", " + firstName + " Student ID:" + studentID + "\n";
            }
           
        }
        
        if (dropCourseStudents.size() == 0)
        {
            scheduledDropped = scheduledDropped + "none";
            waitlistedDropped = waitlistedDropped + "none";
        }
            
        CourseQueries.dropCourse(currentSemester, courseCode);
        ScheduleQueries.dropScheduleByCourse(currentSemester, courseCode);
        DropCourseTextArea.setText(scheduledDropped + "\n" + waitlistedDropped);
        rebuildCourseComboBoxes();
    }//GEN-LAST:event_AdminDropCourseButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CourseSchedulerGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CourseSchedulerGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CourseSchedulerGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CourseSchedulerGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CourseSchedulerGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddSemesterSubmitButton;
    private javax.swing.JButton AdminDropCourseButton;
    private javax.swing.JComboBox<String> AdminDropCourseComboBox;
    private javax.swing.JButton AdminDropStudentButton;
    private javax.swing.JComboBox<String> AdminDropStudentComboBox;
    private javax.swing.JTextArea AdminDropStudentTextArea;
    private javax.swing.JComboBox<String> ChangeCourseComboBox;
    private javax.swing.JButton ChangeSemesterButton;
    private javax.swing.JComboBox<String> ChangeSemesterComboBox;
    private javax.swing.JButton DisplayCourseListStudentsButton;
    private javax.swing.JComboBox<String> DisplayCourseListStudentsComboBox;
    private javax.swing.JComboBox<String> DisplayScheduleStudentComboBox;
    private javax.swing.JTextArea DropCourseTextArea;
    private javax.swing.JTextField FirstNameTextField;
    private javax.swing.JTextField LastNameTextField;
    private javax.swing.JLabel ScheduleCoursesLabel;
    private javax.swing.JTable ScheduledCourseListStudentsTable;
    private javax.swing.JLabel SemesterNameJLabel;
    private javax.swing.JButton StudentDropCourseButton;
    private javax.swing.JComboBox<String> StudentDropCourseComboBox;
    private javax.swing.JTextArea StudentDropCourseTextArea;
    private javax.swing.JTable WaitlistedCourseListStudentsTable;
    private javax.swing.JButton addCourseButton;
    private javax.swing.JTextField addCourseCodeTextField;
    private javax.swing.JTextField addCourseDescriptionTextField;
    private javax.swing.JSpinner addCourseSeatsSpinner;
    private javax.swing.JLabel addCourseStatusLabel;
    private javax.swing.JLabel addSemesterStatusLabel;
    private javax.swing.JTextField addSemesterTextField;
    private javax.swing.JButton addStudentButton;
    private javax.swing.JTextField addStudentIDTextField;
    private javax.swing.JLabel addStudentStatusLabel;
    private javax.swing.JLabel currentSemesterLabel;
    private javax.swing.JComboBox<String> currentStudentComboBox;
    private javax.swing.JButton displayCoursesButton;
    private javax.swing.JTable displayCoursesTable;
    private javax.swing.JButton displayScheduleButton;
    private javax.swing.JTable displayScheduleTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTabbedPane jTabbedPane4;
    private javax.swing.JButton scheduleCourseSubmitButton;
    private javax.swing.JLabel scheduleCoursesStatusLabel;
    private javax.swing.JComboBox<String> selectStudentComboBox;
    // End of variables declaration//GEN-END:variables


}
